alter session set "_ORACLE_SCRIPT"=true;

CREATE USER ADMATENA IDENTIFIED BY "112233"
/
CREATE USER APLATENA IDENTIFIED BY "112233"
/

GRANT CONNECT TO ADMATENA
/
GRANT CREATE SESSION TO ADMATENA
/
GRANT ALL ON ADMATENA.TB_ETLS_ATIVIDADE  TO ADMATENA
/
GRANT ALL ON ADMATENA.TB_ETLS_TAREFA  TO ADMATENA
/

GRANT CONNECT TO APLATENA
/
GRANT CREATE SESSION TO APLATENA
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ADMATENA.TB_ETLS_ATIVIDADE  TO APLATENA
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ADMATENA.TB_ETLS_TAREFA  TO APLTAREFAS
/

GRANT UNLIMITED TABLESPACE TO APLATENA
/
GRANT UNLIMITED TABLESPACE TO ADMATENA
/