alter session set "_ORACLE_SCRIPT"=true;

CREATE USER ADMTAREFAS IDENTIFIED BY "112233"
/
CREATE USER APLTAREFAS IDENTIFIED BY "112233"
/

GRANT CONNECT TO ADMTAREFAS
/
GRANT CREATE SESSION TO ADMTAREFAS
/
GRANT ALL ON ADMTAREFAS.ATIVIDADE  TO ADMTAREFAS
/
GRANT ALL ON ADMTAREFAS.TAREFA  TO ADMTAREFAS
/

GRANT CONNECT TO APLTAREFAS
/
GRANT CREATE SESSION TO APLTAREFAS
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ADMTAREFAS.ATIVIDADE  TO APLTAREFAS
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ADMTAREFAS.TAREFA  TO APLTAREFAS
/

GRANT UNLIMITED TABLESPACE TO APLTAREFAS
/
GRANT UNLIMITED TABLESPACE TO ADMTAREFAS
/